name: GolmonSMP
version: 1.0
api-version: 1.19
author: Fyz
main: sh.fyz.golmonsmp.Main
commands:
  home:
  sethome:
  delhome:
  pronouns:
  tpa:
  tpyes:
  tpno:
  tpaccept:
  tpdeny:
  tpcancel:
  tpundo:
  voterain: